PROFILE = {
    "type": "service_event_recurrence",
    "target_service": "svc-workspace",
    "event_name": "org_policy_revalidate",
    "event_path": "/admin/event",
    "warmup_s": 5,
    "event_duration_s": 5,
    "post_revert_peak_s": 20,
    "peak_rps": 50,
    "request_timeout_s": 3,
    "drain_timeout_s": 20,
    "channels": [f"chan-{index}" for index in range(8)],
    "attempt_paths": [
        {"service": "svc-message", "target": "channel"},
        {"service": "svc-channel", "target": "workspace"},
    ],
    "resource_services": ["svc-message", "svc-channel", "svc-workspace"],
    "capacity_controller_url": "http://capacity-controller:8130/metrics",
    "capacity_target": "workspace",
    "max_workers": 6,
    "timeout_s": 90,
}
