PROFILE = {
    "type": "fixed_pod_restart",
    "target_pod": "svc-message-0",
    "target_service": "svc-message",
    "readiness_path": "/healthz",
    "timeout_s": 180,
    "channels": ["chan-2", "chan-3"],
    "post_ready_wait_s": 15,
    "survivor_profile": "p1_runtime",
    "session_planner": {
        "n_sessions": 256,
        "behavior_seed": 5801,
        "channel_pool_k": 8,
        "channels_per_session": 5,
        "channel_skew": 1.25,
        "action_weights": {
            "session_login": 0.20,
            "session_history": 6.00,
            "session_unread": 1.50,
            "session_post": 3.00,
            "session_thread": 1.00,
            "session_reply": 0.60,
            "session_reaction": 0.35,
            "session_edit": 0.15,
            "session_delete": 0.08,
            "session_file_upload": 0.25,
            "session_file_download": 0.25,
            "session_presence": 0.30,
            "session_search": 0.30,
        },
    },
}
