"""Closed Slack service-event recurrence challenge implementation."""

from __future__ import annotations

import concurrent.futures
import json
import math
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

from .errors import EvidenceError

_SAMPLE = re.compile(
    r"^(?P<name>[a-zA-Z_:][a-zA-Z0-9_:]*)(?:\{(?P<labels>[^}]*)\})?\s+"
    r"(?P<value>[-+]?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][-+]?[0-9]+)?)$"
)
_LABEL = re.compile(r'(?:^|,)([a-zA-Z_][a-zA-Z0-9_]*)="((?:\\.|[^"\\])*)"')


def _request(
    method: str, url: str, *, body: dict[str, Any] | None = None, timeout: float = 5
) -> tuple[int, dict[str, Any]]:
    raw_body = None if body is None else json.dumps(body, separators=(",", ":")).encode()
    request = urllib.request.Request(
        url,
        data=raw_body,
        method=method,
        headers={"accept": "application/json", "content-type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status, raw = response.status, response.read()
    except urllib.error.HTTPError as exc:
        status, raw = exc.code, exc.read()
    except OSError as exc:
        raise EvidenceError(
            f"service-event request failed for {method} {url}: {type(exc).__name__}"
        ) from exc
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise EvidenceError(
            f"service-event returned malformed JSON for {method} {url}: HTTP {status}"
        ) from exc
    if not isinstance(payload, dict):
        raise EvidenceError("service-event response must be a JSON mapping")
    return status, payload


def _text(url: str) -> str:
    request = urllib.request.Request(url, headers={"accept": "text/plain"})
    try:
        with urllib.request.urlopen(request, timeout=5) as response:
            if response.status != 200:
                raise EvidenceError(f"metrics scrape returned HTTP {response.status}: {url}")
            return response.read().decode()
    except (OSError, UnicodeDecodeError) as exc:
        raise EvidenceError(f"metrics scrape failed for {url}: {type(exc).__name__}") from exc


def _parse_metrics(raw: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line_number, raw_line in enumerate(raw.splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _SAMPLE.fullmatch(line)
        if not match:
            continue
        value = float(match.group("value"))
        if not math.isfinite(value):
            raise EvidenceError(f"non-finite metrics sample at line {line_number}")
        labels_raw = match.group("labels") or ""
        labels: dict[str, str] = {}
        matches = list(_LABEL.finditer(labels_raw))
        if labels_raw and "".join(item.group(0).lstrip(",") for item in matches) != labels_raw.replace(",", ""):
            # Validate with a simpler canonical reconstruction below; exposition
            # generated by prom-client uses comma-separated quoted scalar labels.
            consumed = 0
            for item in matches:
                if item.start() != consumed:
                    raise EvidenceError(f"malformed metric labels at line {line_number}")
                consumed = item.end()
            if consumed != len(labels_raw):
                raise EvidenceError(f"malformed metric labels at line {line_number}")
        for item in matches:
            key = item.group(1)
            if key in labels:
                raise EvidenceError(f"duplicate metric label {key!r} at line {line_number}")
            labels[key] = bytes(item.group(2), "utf-8").decode("unicode_escape")
        rows.append({"name": match.group("name"), "labels": labels, "value": value})
    return rows


def _one(rows: list[dict[str, Any]], name: str, labels: dict[str, str] | None = None) -> float:
    matches = [
        row for row in rows
        if row["name"] == name and (labels is None or row["labels"] == labels)
    ]
    if len(matches) != 1:
        raise EvidenceError(
            f"metrics require exactly one {name} sample labels={labels}, found {len(matches)}"
        )
    return matches[0]["value"]


def _snapshot(config: dict[str, Any]) -> dict[str, Any]:
    attempts: dict[str, dict[str, float]] = {}
    resources: dict[str, Any] = {}
    by_service: dict[str, list[dict[str, Any]]] = {}
    for service in config["resource_services"]:
        rows = _parse_metrics(_text(f"http://{service}:8000/metrics"))
        by_service[service] = rows
        resources[service] = {
            "checked_out": _one(rows, "db_pool_checked_out", {}),
            "capacity": _one(rows, "db_pool_capacity", {}),
        }
        if resources[service]["checked_out"] > resources[service]["capacity"]:
            raise EvidenceError(f"pool checked_out exceeds capacity for {service}")
    for path in config["attempt_paths"]:
        service, target = path["service"], path["target"]
        series = [
            row for row in by_service[service]
            if row["name"] == "http_client_attempts_total"
            and row["labels"].get("target") == target
            and isinstance(row["labels"].get("result"), str)
        ]
        if not series:
            raise EvidenceError(f"attempt counter is missing for {service}->{target}")
        values: dict[str, float] = {}
        for row in series:
            result = row["labels"]["result"]
            if result in values:
                raise EvidenceError(f"duplicate attempt result series for {service}->{target}")
            values[result] = row["value"]
        attempts.setdefault(service, {})[target] = sum(values.values())
    controller = _parse_metrics(_text(config["capacity_controller_url"]))
    workers = _one(
        controller,
        "capacity_controller_target_workers",
        {"target": config["capacity_target"]},
    )
    return {"attempts": attempts, "resources": resources, "workers": workers}


def _event(config: dict[str, Any], active: bool) -> dict[str, Any]:
    url = f"http://{config['target_service']}:8000{config['event_path']}"
    status, payload = _request(
        "PUT", url, body={"name": config["event_name"], "active": active}
    )
    values = payload.get("active")
    if status != 200 or not isinstance(values, list) or any(not isinstance(v, str) for v in values):
        raise EvidenceError(f"service-event mutation returned invalid acknowledgement: {payload!r}")
    is_active = config["event_name"] in values
    if is_active is not active:
        raise EvidenceError("service-event acknowledgement does not match requested state")
    return {"status": status, "active": sorted(values), "ts_s": time.time()}


def _event_state(config: dict[str, Any], expected: bool) -> dict[str, Any]:
    url = f"http://{config['target_service']}:8000{config['event_path']}"
    status, payload = _request("GET", url)
    values = payload.get("active")
    if status != 200 or not isinstance(values, list) or any(not isinstance(v, str) for v in values):
        raise EvidenceError("service-event GET returned invalid state")
    if (config["event_name"] in values) is not expected:
        raise EvidenceError("service-event state did not match the required phase")
    return {"status": status, "active": sorted(values), "ts_s": time.time()}


def _drive_phase(
    config: dict[str, Any], challenge_id: str, phase: str, duration_s: int, offset: int
) -> list[dict[str, Any]]:
    count = duration_s * config["peak_rps"]
    start = time.monotonic()

    def one(index: int) -> dict[str, Any]:
        global_index = offset + index
        channel = config["channels"][global_index % len(config["channels"])]
        client = f"v2-event-{challenge_id[-12:]}-{global_index:04d}"
        body = f"service-event-recurrence {client}"
        started = time.monotonic()
        try:
            status, payload = _request(
                "POST",
                "http://svc-message:8000/messages",
                body={"channel_id": channel, "client_msg_id": client, "text": body},
                timeout=config["request_timeout_s"],
            )
            seq = payload.get("seq")
            correct = (
                status in {200, 201}
                and payload.get("client_msg_id") == client
                and isinstance(seq, int)
                and not isinstance(seq, bool)
                and seq > 0
            )
            error = None
        except EvidenceError as exc:
            status, seq, correct, error = 0, None, False, str(exc)
        return {
            "phase": phase,
            "index": global_index,
            "channel_id": channel,
            "client_msg_id": client,
            "text": body,
            "status": status,
            "seq": seq,
            "correct": correct,
            "latency_ms": round((time.monotonic() - started) * 1000, 3),
            "error": error,
        }

    futures: list[concurrent.futures.Future[dict[str, Any]]] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=160) as executor:
        for index in range(count):
            deadline = start + index / config["peak_rps"]
            delay = deadline - time.monotonic()
            if delay > 0:
                time.sleep(delay)
            futures.append(executor.submit(one, index))
        records = [
            future.result(timeout=config["drain_timeout_s"] + config["request_timeout_s"])
            for future in futures
        ]
    records.sort(key=lambda row: row["index"])
    return records


def _readback(records: list[dict[str, Any]]) -> dict[str, Any]:
    accepted = [row for row in records if row["correct"] is True]
    expected = {row["client_msg_id"]: row for row in accepted}
    found: set[str] = set()
    by_channel: dict[str, list[dict[str, Any]]] = {}
    for row in accepted:
        by_channel.setdefault(row["channel_id"], []).append(row)
    for channel, channel_rows in by_channel.items():
        minimum = min(row["seq"] for row in channel_rows)
        after = max(0, minimum - 1)
        pages = 0
        while pages < 32:
            query = urllib.parse.urlencode({"after_seq": after, "limit": 1000})
            status, payload = _request(
                "GET",
                f"http://svc-message:8000/channels/{urllib.parse.quote(channel, safe='')}/messages?{query}",
                timeout=10,
            )
            messages = payload.get("messages")
            if status != 200 or not isinstance(messages, list) or any(not isinstance(row, dict) for row in messages):
                raise EvidenceError(f"service-event history readback is malformed for {channel}")
            for message in messages:
                client = message.get("client_msg_id")
                row = expected.get(client)
                if (
                    row is not None
                    and message.get("seq") == row["seq"]
                    and message.get("body") == row["text"]
                ):
                    found.add(client)
            if len(messages) < 1000:
                break
            last = messages[-1].get("seq")
            if not isinstance(last, int) or last <= after:
                raise EvidenceError("service-event history pagination did not advance")
            after = last
            pages += 1
    return {"expected": len(expected), "found": len(found), "pass": found == set(expected)}


def run(config: dict[str, Any], challenge_id: str) -> dict[str, Any]:
    initial_event = _event_state(config, False)
    snapshots: dict[str, Any] = {"initial": _snapshot(config)}
    offset = 0
    warmup = _drive_phase(config, challenge_id, "warmup", config["warmup_s"], offset)
    offset += len(warmup)
    enabled = _event(config, True)
    try:
        _event_state(config, True)
        event = _drive_phase(
            config, challenge_id, "event_active", config["event_duration_s"], offset
        )
        offset += len(event)
        snapshots["active"] = _snapshot(config)
    finally:
        # A verifier-induced transient must never remain armed after an error.
        disabled = _event(config, False)
    reverted_state = _event_state(config, False)
    snapshots["reverted"] = _snapshot(config)
    post = _drive_phase(
        config,
        challenge_id,
        "post_revert_peak",
        config["post_revert_peak_s"],
        offset,
    )
    snapshots["final"] = _snapshot(config)
    final_event = _event_state(config, False)
    records = [*warmup, *event, *post]
    readback = _readback(records)
    completed = sum(1 for row in records if 200 <= row["status"] < 300)
    correct = sum(1 for row in records if row["correct"])
    traffic = {
        "scheduled": len(records),
        "attempted": len(records),
        "completed": completed,
        "correct": correct,
        "readback": readback,
        "by_phase": {
            phase: {
                "scheduled": sum(1 for row in records if row["phase"] == phase),
                "completed": sum(1 for row in records if row["phase"] == phase and 200 <= row["status"] < 300),
                "correct": sum(1 for row in records if row["phase"] == phase and row["correct"]),
            }
            for phase in ("warmup", "event_active", "post_revert_peak")
        },
        "records": records,
    }
    ratios: dict[str, Any] = {}
    denominator = traffic["by_phase"]["post_revert_peak"]["scheduled"]
    for path in config["attempt_paths"]:
        service, target = path["service"], path["target"]
        before = snapshots["reverted"]["attempts"][service][target]
        after = snapshots["final"]["attempts"][service][target]
        if after < before:
            raise EvidenceError(f"attempt counter decreased for {service}->{target}")
        delta = after - before
        ratios.setdefault(service, {})[target] = {
            "delta": delta,
            "logical_requests": denominator,
            "attempts_per_logical_request": delta / denominator,
        }
    resources: dict[str, Any] = {}
    for service in config["resource_services"]:
        samples = [snapshot["resources"][service] for snapshot in snapshots.values()]
        capacities = [sample["capacity"] for sample in samples]
        resources[service] = {
            "capacity_unchanged": len(set(capacities)) == 1,
            "capacity": capacities[-1],
            "max_checked_out": max(sample["checked_out"] for sample in samples),
        }
    workers = [snapshot["workers"] for snapshot in snapshots.values()]
    return {
        "pass": (
            traffic["scheduled"] == traffic["attempted"] == traffic["completed"] == traffic["correct"]
            and readback["pass"] is True
            and all(item["capacity_unchanged"] for item in resources.values())
            and max(workers) <= config["max_workers"]
        ),
        "event": {
            "initial": initial_event,
            "enabled": enabled,
            "disabled": disabled,
            "reverted": reverted_state,
            "final": final_event,
        },
        "traffic": traffic,
        "attempts": ratios,
        "resources": resources,
        "capacity_controller": {
            "target": config["capacity_target"],
            "maximum_workers": max(workers),
            "ceiling": config["max_workers"],
        },
        "snapshots": snapshots,
    }
